### ISSUE TITLE
Issue showing outline material on entity 

### ISSUE THREAD

**Issue by jeremielim** [gonchar/GoncharKit#1]
<img width="143" alt="image" src="https://github.com/gonchar/GoncharKit/assets/692129/a1816310-7927-4e35-aea3-d122ce76b144">

I might be doing something wrong but I tried adding a new material directly in the parameter but it can't find it

```swift
// add outline material
value.entity.components[ModelComponent.self] = value.entity.components[ModelComponent.self]?.generateOutlineMeshParts(
  outlineMaterial: UnlitMaterial(color: .red),
  offset: offsetValue
)
```

**Comment by gonchar** [comment]
looks like smth is wrong on your side

<img width="402" alt="Screenshot 2024-03-16 at 16 35 58" src="https://github.com/gonchar/GoncharKit/assets/1416917/495e868f-1c06-49f6-9934-304e15e766cb">

```swift
scene.forEach(withComponent: ModelComponent.self) { entity, comp in
  entity.components[ModelComponent.self] = entity.components[ModelComponent.self]?.generateOutlineMeshParts(
    outlineMaterial: UnlitMaterial(color: .red),
    offset: 0.02
  )
}
```

**Comment by gonchar** [comment]
you can send me sample xcode project to reproduct the bug
